pact-foundation/docs.pact.io

- docs/pact_broker/can_i_deploy.md
I found this type while reading the documentation on https://docs.pact.io/pact_broker/can_i_deploy. This PR aims at fixing it.
> Fix a typo. "Big bag -> Big bang".

- website/docs/implementation_guides/workshops.md
Adding a link to my Udemy Course which introduces Contract Testing from end-to-end
> docs: Add Udemy course link

- website/docs/pact_broker/webhooks/template_library.md
Update Azure DevOps template
Up URL API to 6.0
Change name from "Visual Studio Team Services" to "Azure DevOps"
Change format from "text" to "json"
Add ref
> docs: Update Azure DevOps template

- website/docs/pact_broker/advanced_topics/provider_verification_results.md
- website/sidebars.json
Move that advanced topic page to proper sidebar category and fix broken
link to consumer version selectors page.
https://docs.pact.io/pact_broker/advanced_topics/provider_verification_results
> Fix broken link on provider verification results page

- website/docs/pact_broker/advanced_topics/api_docs.md
all of the links had "/api_docs/" repeated in the path (ex: "https://docs.pact.io/pact_broker/advanced_topics/api_docs/api_docs/pacticipant")  and resulted in a page not found error for all links under advanced topics
> fix: Update api_docs.md

- website/docs/faq/convinceme.md
I have read this litmus test a hundred times and I think the negation is wrong. I've proposed a one-contraction fix. 
Other alternatives to consider would be: 
* "The litmus test is this: if you spend a lot of time maintaining E2E environments or have constant challenges managing the tests, then it's time for another approach"
* "The litmus test is this: if you can look someone straight in the eye and say you get a lot of value out of your E2E tests without significant time investment, you can carry on, but otherwise it's time for another approach."
> docs: fix litmus test wording

- website/docs/pact_broker/tags.md
The link about the blog post "Enter the Pact Matrix. Or, how to decouple the release cycles of your microservices" is not working. 
I have changed it for what I think is a currently working link of the same blog post
> Fix broken link - Pact broker tags section

- website/docs/implementation_guides/swift.md
[PactSwift](https://github.com/surpher/PactSwift) is out in the wild and seems that eBay, John Lewis, ANZ, Latitude Financial Services are successfully using it. 
Updates the implementation guide page for Swift and adds the link to PactSwift project.
> docs: add link to PactSwift

- website/docs/telemetry.md
- website/docusaurus.config.js
- website/sidebars.json
The purpose of this PR is to outline the purpose, intention and specifics of the telemetry that will be rolled out as part of ongoing development of Pact. This document is the outcome of discussions with Pact maintainers and describes the type of data that will be collected, as well as how to opt-out of sending telemetry.
> feat: Documentation detailing new telemtry that is being introduced into Pact

- website/docs/recipes.md
Links resolving to https://docs.pact.io/recipes/recipes/graphql when viewed from recipes pages
see slack thread for mention of issue
https://pact-foundation.slack.com/archives/CAN147DFD/p1645115313768419?thread_ts=1641990628.004600&channel=CAN147DFD&message_ts=1645115313.768419
> docs - update recipes relative links

- website/docusaurus.config.js
Setting `trailingSlash: false` generates `folder/file.html`, rather than `folder/file/index.html`. This means that when netlify gets a request for `folder/file` it returns `folder/file.html`, and when it receives a request for `folder/file/` (trailing slash) it redirects to `folder/file`. Previously it was the other way around.
Because `folder/file` returns an actual file now, and not a redirect, the URl matches the canonical URl in the sitemap.xml file, and so this should fix the Angolia Crawler issue.
> chore: disable trailing slash

- website/docusaurus.config.js
Add metadata as per https://docusaurus.io/docs/api/themes/configuration#metadata to enable doc search again
___
**Issue**
Doc search on docs.pact.io is now working
**Cause**
Looking the at the search request that is made from the [docs pages]( https://docs.pact.io/)., it doesn't return any results.
It appears to be down to the `requests.params.facetFilters` namely the `docusaurus_tag`'s
They are set to `["language:en",["docusaurus_tag:default","docusaurus_tag:docs-default-current"]]`
if I rerun the request dropping the array of `docusauraus_tag`'s appears to fix the request.
I tried isolating either of the `docusauraus_tag`'s and removing them from the array of `facetFilters` to no avail.
**Remediation**
https://v1.docusaurus.io/docs/en/search.html#extra-search-options …
> fix: addDocusaurusMeta

- website/blog/2018-10-18-publishing-pact-verification-statuses-to-github.md
- website/blog/2018-24-07-contract-testing-a-graphql-api.md
- website/blog/2019-01-05-announcing-pactflow-our-managed-pact-broker.md
- website/blog/2019-29-05-v3-provider-state-support-added-to-pact-ruby-js-go-dotnet.md
- website/blog/2020-11-03-automatic-data-clean-up-in-the-pact-broker.md
- website/blog/2020-24-02-how-weve-fixed-the-biggest-problem-with-the-pact-workflow.md
- website/blog/2020-24-02-introducing-wip-pacts.md
Closes #54 - We should probably shut down the old blog after. will check for refs across the docs if there are any
For some reason two posts, with the date stamp `2020-24-02` show up as 2021, they will update to dates ahead of 2020 🤷🏾‍♂️
> chore: add blog posts from http://blog.pact.io/

- website/docs/provider/recommended_configuration.md
While working through some of the setup docs, I noticed some small typos on the Ruby `Recommended configuration for verifying pacts` page. One missing comma, and some references that could be leveraging an already declared variable. 
If you copy paste the recommended code without having passing in a `GIT_BRANCH` env variable, a `rake pact:verify` command would fail with this error:
```bash
{"errors":{"consumerVersionSelectors":["tag can't be blank at index 0"]}} (Pact::Hal::ErrorResponseReturned)
```
Ran `rake pact:verify` with these small changes included in a local project.
Preview new page at -> https://deploy-preview-135--docs-pact-io.netlify.app/provider/recommended_configuration
> chore: small typos in recommended setup

- website/docs/consumer/recommended_configuration.md
Minor tweak to address a page that has not been updated to refer to `branch` as the new standard, in favor of tags.
https://docs.pact.io/consumer/recommended_configuration
> feat: update pact-broker recommendation from tags to branch

- website/docs/faq/convinceme.md
The previous link (https://github.com/pact-foundation/pact-ruby/wiki/FAQ\#how-does-pact-differ-from-vcr) doesn't seem to be valid for provided description (See "..."  for more examples of similar technologies.).
> Actualize link to comparison with similar technologies

- website/docs/getting_started/how_pact_works.md
See the Alistair Cockburn original definition as a reference: https://alistair.cockburn.us/hexagonal-architecture/. In the other part of the document, it's correctly used as _Adapter_.
> Updated typo in Hexagonal Architecture name, it should be "Ports and Adapters", not "Ports and Adaptors"

- website/docs/pact_broker/branches.md
The anchor should link to `#automatic-branch-creation-from-first-tag` rather than `#configuring-the-branch-when-publishing-verification-results`.
> fix: fix anchor link that links to wrong heading

- website/docs/consumer/contract_tests_not_functional_tests.md
I would suggest staying strict with the terminology:
- Use the noun "test" and the verb "test" to specify the actions done by, and only by, the _consumers_;
- Use the noun "verification" and the verb "verify" to specify the actions done by, and only by, the _providers_.
So, in the context of contract testing with Pact, a _provider_ would never test; a _provider_ would (only) verify.
If I could be even more pedantic, I would say that while a _provider_ does verify a Pact, a _consumer_ does *not** test a Pact, but test **with** a Pact.
> fix: Strict usage of "test" for consumer and "verification" for provider

- website/docs/community_repos.md
Adds entry for demo of [pact-message-ruby gem](https://github.com/pact-foundation/pact-message-ruby) to `community_repos.md`
> docs: Update community_repos.md

- website/docs/pact_broker/advanced_topics/consumer_version_selectors.md
- website/docs/pact_broker/advanced_topics/pending_pacts.md
- website/docs/pact_broker/advanced_topics/wip_pacts.md
- Updates Pending pacts page to reference branches, and new consumer version selectors
- https://deploy-preview-178--docs-pact-io.netlify.app/pact_broker/advanced_topics/pending_pacts
- Updates consumer version selector page code snippets to support branches/environments
- https://deploy-preview-178--docs-pact-io.netlify.app/pact_broker/advanced_topics/consumer_version_selectors#code-examples-with-branches
- Adds links to source code/docs for respective language implementations
- https://deploy-preview-178--docs-pact-io.netlify.app/pact_broker/advanced_topics/consumer_version_selectors#docs
> More branch updates

- website/docs/roadmap/feature_support.md
Publishing pacts directly from Pact-Net is no longer possible in version 4. Docs say, CLI ought to be used.
> Correct table entry in feature_support.md

- website/docs/faq.md
From pact-foundation/pact-ruby/... to  docs.pact.io, to prevent users from having to click the redirect links.
> Updated links

- website/docs/implementation_guides/python.md
One of the main changes in pact v3 was the addition of the message queue format; users should be informed as soon as possible that Pactman is not a viable solution for validating message queue pacts, rather than wading through github issues like I had to do. 
https://github.com/reecetech/pactman/issues/68
> wiki: Pactman does not support message queues

- website/docs/pact_broker/advanced_topics/consumer_version_selectors.md
I checked all the programming language related links in the `consumer_version_selectors.md` document.
And only the last golang one was broken.
> fix: broken golang link in consumer_version_selectors.md

- website/docs/docker.md
- musl binaries now avail in core and consumed in most languages
- (still require support in pact-go/pact-net) (link to RFC's)
- glibc version req dropped to 2.23 in shared core
- ruby impl
- bash requirement removed from pact-ruby-standalone
- mark pact-go / pact-net as not supporting alpine (yet)
- update pact ecosystem to reflect pact-php v10 using rust core
- Add docker images for each supported lang in code tabs
> docs: update docker guidance

- website/docs/help/enabling-debug-logging.md
Clarify that Pact PHP `9.x` and `10.x` works exactly the same, with a slight different on the log level values.
> docs: Combine Pact PHP logging info

- website/docs/implementation_guides/workshops.md
* Link the version of .NET workshop that aligns with the other workshops
Why?
* I recently wanted to learn more about pact and followed the workshop linked originally
* Only after running into some issues I found out that there is a more recent version
* Aligns .NET workshop contents with workshops in other languages
> docs(workshops.md): Link more recent version of the .NET workshop

- website/docs/implementation_guides/other_languages.md
- website/docs/implementation_guides/overview.md
- website/docs/implementation_guides/python.md
- website/docusaurus.config.js
- website/sidebars.json
Trialling out a different landing page for the pact docs section, which currently drops into the cli tools overview
https://deploy-preview-316--docs-pact-io.netlify.app/implementation_guides/overview
> docs: updated entry point for language/tooling docs

- website/docs/getting_started/how_pact_works.md
The link to Kafka University Message Pact Async on the How Pact Work is using localhost:3000, which is inaccessible.
> fix pact message link

- website/docs/pact_nirvana.md
It seems like something got a little jumbled in the text for this page.
I'm pretty sure the intended word here was **may**, but what was rendered was a solitary `y`.
```diff
- each team   y have different processes
+ each team may have different processes
```
> fix typo in pact_nirvana.md

- website/docs/consumer.md
I took a shot at extracting the best practices in the video, and transposing them into a useful set of rules people could use to review tests.
I'm not 100% happy with them, but thought I'd share my thinking (the "Bug Catcher" rule I'm struggling to define clearly, but probably because it's quite a difficult thing to generalise but also give concrete examples concisely).
> docs(consumer): create list of best practice rules
