website/docusaurus.config.js, website/package-lock.json, website/package.json
Fixes https://github.com/facebook/docusaurus/issues/3363
=> upgrade to docusaurus alpha 62

website/docs/pact_broker/advanced_topics/consumer_version_selectors.md, website/src/pages/users.js
@bethesque I have done a first page. Can chat to you on our overlap tomorrow morning on slack about a couple of things but if you give me the list I can probably do the rest once you're happy with this
=> fix: consumer selector code fixes

website/docs/pact_broker/webhooks/template_library.md
If it's not too much work, can this repo/PR have the Haktoberfest labels added so it "counts" 😄 
https://hacktoberfest.digitalocean.com/hacktoberfest-update
=> Update Bamboo build trigger example

website/docs/pact_broker/advanced_topics/consumer_version_selectors.md
Add more Java examples, s. https://github.com/DiUS/pact-jvm/issues/1149#issuecomment-711079612
=> chore: Add missing examples for Java consumer version selector

website/docs/pact_broker/advanced_topics/consumer_version_selectors.md
Fixes https://github.com/pact-foundation/pact-python/issues/149
=> docs: Add consumer version selectors examples for Python

website/docs/pact_broker/webhooks/template_library.md
Additional webhook template for triggering GitHub builds from pactflow
=> docs: Adding GitHub build trigger to templates

website/docs/getting_started/sharing_pacts.md
Just some small things I noticed as I read through the document.
=> docs: grammar and spelling fixes

website/docs/pact_broker/advanced_topics/api_docs.md
Fixes #51
How to test:
1. Go to website folder
2. Run `npm install`
3. Run `npm run build`
4. Inspect end result
=> Fix broken links on pact broker api docs page

website/docs/pact_broker/advanced_topics/consumer_version_selectors.md
Add c# customer version selectors examples.
=> docs: Customer version selector examples

website/docs/pact_broker/webhooks/template_library.md
=> docs: update slack notifications

website/docs/pact_broker/advanced_topics/consumer_version_selectors.md
the order of the languages was different in some of the list, fixed them
=> fix: order of languages

website/docs/pact_broker/webhooks/template_library.md
Expand examples to include referencing a custom pipeline and using variables for parameters.
=> docs: update webhook docs for bitbucket

website/sidebars.json
[PactSwift](https://github.com/surpher/PactSwift) implementation supports provider verification as well.
=> docs: Rename sidebar item for Swift implementation

website/docs/recipes/kafka.md
docs: Added examples for using Messaging with Kafka and JSON messages
=> docs: Update kafka.md

website/docs/recipes/kafka.md
docs: Add recipe for Kafka Schema Registry compliant JSON
=> docs: Add Kafka Schema Registry compliant JSON

README.md
=> docs: Update search details

website/blog/2018-07-10-welcome.md, website/docs/blogs_videos_and_articles.md
update blog link(s) to docs.pact.io/blog
=> docs: update blog link

website/src/css/custom.css
=> fix: update link contrast

website/docs/getting_started/comparisons.md
=> Fixed phrasing in comparisons.md

README.md, website/docs/help/how_to_ask_for_help.md, website/docs/pact_nirvana/step_1.md, website/docs/pact_nirvana/step_3.md, website/docs/pact_nirvana/step_5.md, website/docs/pact_nirvana/step_7.md
Whilst implementing Pact in my organisation and reading through a lot of the documentation, I noticed a handful of typos.
So here is a minor PR to hopefully resolve them.
=> Fixed a few typos

website/docs/pact_broker/webhooks.md
Webhooks are relevant with Platinum step (6)
=> fix: Fix link that links to wrong page

website/docs/blogs_videos_and_articles.md
See https://twitter.com/you54f/status/1581051579855417344
I had to hunt a bit for the source, so I've linked to the source from the suggestion to open a PR.
=> add Holly Cummins and Eric Deandrea Devoxx talk

website/docs/blogs_videos_and_articles.md, website/docs/community_repos.md
Add posts from
- https://twitter.com/edeandrea/status/1583931223742631936?s=20&t=5OzQaUNd6ckQPW67vQhwDg
- https://twitter.com/rogervinasalcon/status/1584461428031098880?s=20&t=nn_1aUiy3hG6RMyrG3vgrQ
=> feat: community posts/repos

website/docs/events.md
Add new event for plugins framework launch
=> docs: add new event for plugins framework launch

website/docs/events/plugins-framework-launch.md
Creating page for plugins launch webinar! Woo hoo!
=> docs: plugins framework launch webinar invite

website/blog/2022-10-25-pact-open-source-update-october-2022.md
Thank you folks for the shout out, really means a lot 🤗
This PR introduces:
* Fixing the Snyk name typo
* Updating the blog post link from Medium to my own blog
=> docs: typo and fix link

website/docs/docker.md
I'm not sure how not to trigger changing the end of the file with initiating PR from GitHub UI :(
=> Drop duplicated word in the sentence

website/blog/2022-11-17-pact-facts-a-history-lesson.md
A lot happens in 10 years. We’ve seen it all here at Pact, from the proliferation of micro services, to ever increasing protocols like [Protobufs](https://developers.google.com/protocol-buffers), [GraphQL](https://graphql.org/), transports such as [gRPC](https://grpc.io/), [Websockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) and [MQTT](https://mqtt.org/), [EventDrivenArchitectures](https://en.wikipedia.org/wiki/Event-driven_architecture) and [data pipelines](https://www.youtube.com/watch?v=6kEGUCrBEU0) or emerging standards such as [OpenAPI](https://www.openapis.org/), [AsyncAPI](https://www.asyncapi.com/) and [CloudEvents](https://cloudevents.io/).
As we launch our [Pact Plugin Framework](https://docs.pact.io/implementation_guides/pact_plugins) bringing you new …
=> blog: pact path to plugins

website/docs/users/case_studies.md
Updated the focus of this page Pact use cases; Pactflow second
=> docs: edit case studies

website/docusaurus.config.js
Add rust and java syntax highlighting, and some others.
Resolves https://github.com/pact-foundation/docs.pact.io/issues/185
=> add additional prism syntax highlighting

website/docusaurus.config.js, website/src/css/custom.css
=> feat: add 2022 oss survey banner

website/docs/pact_broker/webhooks/template_library.md
Updating the Teamcity example with a sample that adds to the environment parameters of the Teamcity build
=> docs: Update Teamcity example

website/src/css/custom.css
After fix:
https://user-images.githubusercontent.com/13126965/208039544-83455f66-7d26-4c1f-8c18-e4af45b51e80.mov
=> fix: search container z-index on small viewport

website/docs/help.md
Changed AMA event to Getting Started series
=> docs: updated AMA event

website/docs/users/case_studies.md
=> docs: update case study

website/blog/2023-03-21-pact-open-source-update-mar-2023.md, website/blog/2023-03-22-pact-open-source-update-mar-2023.md
Link:- https://deploy-preview-239--docs-pact-io.netlify.app/blog/2023/03/22/pact-open-source-update-mar-2023
Link once deployed :- https://docs.pact.io/blog/2023/03/22/pact-open-source-update-mar-2023
=> docs: march blog

website/blog/2023-05-25-pact-open-source-update-may-2023.md, website/docs/contributing/ci.md, website/docs/diagrams/ecosystem.md, website/docs/users/community_corner/adam_cox_interview_may2023.md, website/docusaurus.config.js, website/package.json, website/sidebars.json, website/src/css/custom.css, website/yarn.lock
Main Blog - https://deploy-preview-264--docs-pact-io.netlify.app/blog/2023/05/25/pact-open-source-update-may-2023
New section - Community Corner - Adam Cox - https://deploy-preview-264--docs-pact-io.netlify.app/users/community_corner/adam_cox_interview_may2023
New Contributing Section - Ci/CD Systems https://deploy-preview-264--docs-pact-io.netlify.app/contributing/ci
New Guide - Pact Ecosystems - https://deploy-preview-264--docs-pact-io.netlify.app/diagrams/ecosystem
=> May 2023 post

website/package.json, website/yarn.lock
Updates docusaurus's three components in a single PR otherwise they end up in a broken state in separate dependabot PR's
=> chore(deps): update docusaurus to 2.4.3

website/blog/2023-10-31-pact-open-source-update-oct-2023.md
Draft URL :- https://deploy-preview-293--docs-pact-io.netlify.app/blog/2023/10/31/pact-open-source-update-oct-2023
=> docs: oct 2023 blog

website/blog/2024-02-19-pact-open-source-update-feb-2024.md
Draft link
https://deploy-preview-309--docs-pact-io.netlify.app/blog/2024/02/19/pact-open-source-update-feb-2024
=> blog: feb 2024 

website/blog/2024-02-21-deleting-branches-automatically.md
Draft link:- https://deploy-preview-311--docs-pact-io.netlify.app/blog/2024/02/21/deleting-branches-automatically
=> blog: delete branches

website/blog/2024-03-26-pact-open-source-update-mar-2024.md
| name | link |
| -- | -- |
| preview | https://deploy-preview-314--docs-pact-io.netlify.app/blog/2024/03/26/pact-open-source-update-mar-2024 |
| live | https://docs.pact.io/blog/2024/03/26/pact-open-source-update-mar-2024 |
Note: Live link, not published yet, link just provided for anyone creating content which references the published url 👍🏾
=> docs: mar 2024 blog draft

website/blog/2024-04-23-pact-open-source-update-may-2024.md
| Type |  URL | Available | 
| -- | -- | -- |
| Preview | https://deploy-preview-323--docs-pact-io.netlify.app/blog/2024/04/23/pact-open-source-update-may-2024 | ✍️ |
| Live | https://docs.pact.io/blog/2024/04/23/pact-open-source-update-may-2024 | ⏳ |
=> blog: add may 2024 blog

website/blog/2024-06-25-pact-open-source-update-june-2024.md, website/blog/2024-07-26-pact-open-source-update-july-2024.md, website/blog/2024-07-30-pact-open-source-update-july-2024.md
| Type |  URL | Available | 
| -- | -- | -- |
| Preview |  https://deploy-preview-334--docs-pact-io.netlify.app/blog/2024/07/26/pact-open-source-update-july-2024 | ✍️ |
| Live | https://docs.pact.io/blog/2024/07/26/pact-open-source-update-july-2024 | ⏳ |
=> blog: july 2024

website/docs/blogs_videos_and_articles.md
The article explains the concept of consumer-driven APIs. It includes an example in Java and Spring, demonstrating three integrated APIs and using Pact tests to verify the contract between them.
The article are available on this link: https://medium.com/@augustocolombelli/contract-tests-apis-guided-by-consumers-caf8f2460e7c
The repository with the example are available on this link: https://github.com/augustocolombelli/pact-contract-test/
=> Add article about APIs guided by consumers using Pact test

website/blog/2024-08-27-pact-open-source-update-aug-2024.md, website/blog/2024-08-29-pact-open-source-update-aug-2024.md
| Type |  URL | Available | 
| -- | -- | -- |
| Preview |  https://deploy-preview-337--docs-pact-io.netlify.app/blog/2024/08/29/pact-open-source-update-aug-2024 | ✅  |
| Live | https://docs.pact.io/blog/2024/08/29/pact-open-source-update-aug-2024 | ⏳ |
=> blog: add August blog

website/docs/blogs_videos_and_articles.md
I am happy to share my article that compares 3 API development methodologies and showcases how Pact can be used to improve the development.
https://openvalue.blog/posts/2023/11/26/communicating_our_apis_part2/
I'll also be giving this as a talk in Devoxx Morocco next month https://devoxx.ma/talk/?id=12271.
Would be happy to have any feedbacks.
=> Add Three methodologies of API Development article

website/blog/2025-03-07-pact-open-source-update-feb-2025.md
Preview Link
- https://deploy-preview-376--docs-pact-io.netlify.app/blog/2025/03/07/pact-open-source-update-feb-2025
Live Link
- https://docs.pact.io/blog/2025/03/07/pact-open-source-update-feb-2025
=> blog: add feb 2025 blog
